image: node:10

pipelines:
  branches:
    master:
      - step:
          name: "Build both Admin and Redemption projects"
          caches:
            - node
          script:
            - npm run clean
            - npm install --quiet
            - ng build --prod
            - ng build --prod --project="redemption"
          artifacts: # defining the artifacts to be passed to each future step.
            - dist/**
      - step:
          # set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables
          name: Deploy to S3
          # deployment: test   # set to test, staging or production
          # trigger: manual  # uncomment to have a manual step
          image: atlassian/pipelines-awscli
          script:
            - aws s3 sync --delete dist/wallet-topup-admin/ s3://admin.wallettopup.co.uk
            - aws s3 sync --delete dist/redemption/ s3://redemption.wallettopup.co.uk
