image: node:10

pipelines:
  branches:
    master:
      - step:
          name: "Build, test"
          caches:
            - node
          script: 
            - npm install --quiet
            - npm run build-prod
          artifacts: # defining the artifacts to be passed to each future step.
            - dist/**
      - step:
          # set AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY as environment variables
          name: Deploy to S3
          # deployment: test   # set to test, staging or production
          # trigger: manual  # uncomment to have a manual step
          image: atlassian/pipelines-awscli
          script:
            - aws s3 sync --delete dist/ s3://cloud.admin.wallettopup.com
