image: node:10

pipelines:
  branches:
    master:
      - step:
          name: "Build both Admin and Redemption projects"
          caches:
            - node
          script:
            - npm run clean
            - npm install --quiet
            - npm run build-prod
            - npm run build-prod-redemption
          artifacts:
            - dist/**
      - step:
          # AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY are set as environment variables on BitBucket
          name: Deploy to S3
          trigger: manual
          image: atlassian/pipelines-awscli
          script:
            - aws s3 sync --delete dist/wallet-topup-admin/ s3://admin.wallettopup.co.uk
            - aws s3 sync --delete dist/redemption/ s3://redemption.wallettopup.co.uk
