image: node:10

pipelines:
  branches:
    master:
      - step:
        name: "Build, test"
        caches:
          - node
        script: 
          - npm install --quiet
          - npm run test
          - npm run build-prod
        artifacts: # defining the artifacts to be passed to each future step.
          - dist/**
      - step:
        name: Deploy to production (Aws S3)
        deployment: production
        script:
          # install aws cli
          - pip install awscli --upgrade
          - s3 --region "<region>" rm s3://<bucket-name>
          - s3 --region "<region>" sync . s3://<bucket-name>